name: Daily SixtySecondsNews

on:
  schedule:
    - cron: '0 2 * * *'  # 每天10:00（北京时间，GitHub Actions 使用UTC时间，需减8小时）
  workflow_dispatch:

jobs:
  run-news-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: Run SixtySecondsNews script
        env:
          WEBHOOK_KEY: ${{ secrets.WEBHOOK_KEY }}
        run: |
          sed -i "s/webhook_key = .*/webhook_key = \"$WEBHOOK_KEY\"  # 替换为实际的webhook key/" 60s.py
          python 60s.py
